GET http://localhost:3000/api/v1/tasks

###

POST http://localhost:3000/api/v1/tasks
Content-Type: application/json

{
    "name": ""
}

###

GET http://localhost:3000/api/v1/tasks/123

###

PATCH  http://localhost:3000/api/v1/tasks/123
Content-Type: application/json

{
    "name": "bruno",
    "age": 23
}

###

DELETE http://localhost:3000/api/v1/tasks/123